class BadRequestError(Exception):
    pass

class InternalError(Exception):
    pass